server:
  port: 8080
spring:
  application:
    name: "ingeneo_services"
  datasource:
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQL95Dialect"
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        proc:
          param_null_passing: true
        jdbc:
          lob:
            non_contextual_creation: true
